# Generated by Django 2.1.2 on 2018-12-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ibm_API_Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('api_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ibm_domain',
            fields=[
                ('domain', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ibm_Hash',
            fields=[
                ('hash', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('risk', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ibm_Ip',
            fields=[
                ('ipadd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.FloatField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ibm_Url',
            fields=[
                ('url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IPLocation',
            fields=[
                ('ipadd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('isp', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ipvoid_Ip',
            fields=[
                ('ipadd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_Total_Hash',
            fields=[
                ('hash', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=500)),
                ('md5', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=200)),
                ('sha1', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=1000)),
                ('blacklist', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_Total_Scan',
            fields=[
                ('file', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=200)),
                ('shal', models.CharField(max_length=200)),
                ('blacklist', models.CharField(max_length=5000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_Total_Url',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=500)),
                ('blacklist', models.CharField(max_length=1000)),
            ],
        ),
    ]
