# Generated by Django 2.1.2 on 2018-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virus_total_hash',
            name='score',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
