# Generated by Django 2.1.2 on 2018-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20181213_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ibm_API_Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('api_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_Total_Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=200)),
            ],
        ),
    ]
